### ISSUE TITLE
Implement AMQP application properties

### ISSUE THREAD

**Issue by Jakingtosch** [lulf/dove#21]
I think AMQP application properties are also missing to gain traction for this library. A lot of other implementations are using them to transport additional data not encoded in the message.

3.2.5    Application Properties  
`<type name="application-properties" class="restricted" source="map" provides="section">
<descriptor name="amqp:application-properties:map" code="0x00000000:0x00000074"/>
</type>`

Source: https://www.amqp.org/sites/amqp.org/files/amqp.pdf -> 3.2.5 (page 78)

**Comment by lulf** [comment]
@Jakingtosch You should be able to set application properties using something like the following:

```
properties = HashMap::new();
properties.insert(Value::String("key".to_string()), Value::String("value".to_string());
let message = Message {
    ...
    application_properties(Some(properties)),
}
```

I admit this is badly documented, but it should be possible at least...

**Comment by Jakingtosch** [comment]
Great, thank you so much for the hint :)
I'll try it!
