### ISSUE TITLE
Owned message access

### ISSUE THREAD

**Issue by Gelbpunkt** [lulf/dove#26]
Hi there, I would like to use your crate to interact with RabbitMQ. As I send a lot of JSON around, I want to use [simd-json](https://docs.rs/simd-json/0.3.25/simd_json/serde/fn.from_slice.html) for reading and writing.
simd-json requires mutable access to what it writes or reads, so I need to own the `MessageBody` to mutate it.
However, `delivery.message()` returns a borrowed reference - would it be possible to make an option to take the message instead of referencing it?

**Comment by lulf** [comment]
I think thats a good idea. I've implemented a take_message() method on delivery here: https://github.com/lulf/dove/pull/27
