### ISSUE TITLE
Upstream changes from fork

### ISSUE THREAD

**Issue by kellerkindt** [lulf/dove#29]
Heyho,

I've been fixing and patching dove [on my fork](https://github.com/kellerkindt/dove).
The changes to date are:
  * Add [AMQP 1.0 Apache Legacy filter](https://www.amqp.org/specification/1.0/filters)
     * 0b1c4b06c43ecf9ba6964b351e751505f1b1c1fa
     * 693f8da11fe45fc28695e52470a7511af097b7fb
     * b389ae04eaf222f4afe35037a72a94cb28f0d70e
     * 3c66de861e098913542868038fccc2dcce64594b
  * Fix ApplicationProperties encoding
    * ad24f77a208c97129cee7c79110f4e528017da6d
  * Properly propagate disconnects
    * df0d4f46a7772118fd6646ac73fac74886c5943a
  * Remove blocking code in async-contexts, locks and unused cross-references
    * 4e861bae3ada9ae5850a6ae6dc932fc04d53f1dd
    * f08efcdacfc9932d1903fb1d5034b8831d6b5c02
    * 7396ac7f835d7eb7e45bbf10d99b0f7ab12ac670
    * 552c70ab92d7c882f23d924eb24deffd7c8fb98a

There will probably more commits in the coming days, but I already wanted to give a heads up info. Feel free to pull in those changes, or if you prefer me to put up PRs, I could do that too.

**Comment by lulf** [comment]
@kellerkindt Thanks for making me aware! Those changes look great. I have just pulled them in by rebasing on your main branch.

Let me know if you want/need to publish a new version of the crate. Also, don't hesitate to raise PRs in the future.
