### ISSUE TITLE
Invalid SASL initial response

### ISSUE THREAD

**Issue by luos** [lulf/dove#37]
Hi,

I was testing this library and noticed that the SASL initial response contains the username twice. Looking at RabbitMQ and some other clients it looks like it's an error, what do you think? 

Here: 

https://github.com/lulf/dove/blob/3d9acac1fb514d2baf86573a9afd25e2f01800b2/src/sasl.rs#L127-L149

**Comment by grs** [comment]
SASL PLAIN defines the message as an optional authzid followed by an authcid, followed by the password. The implementation here uses the username for both authzid and authcid. (https://datatracker.ietf.org/doc/html/rfc4616#section-2)

**Comment by luos** [comment]
Hi,

Thanks for explaining and the link, I tried to look for this in the RFC but could not find it.
